#!/usr/bin/env bash
#install and configure HAproxy

sudo apt update
sudo apt install -y haproxy

SERVER_CONFIG=" 
frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 141730-web-01 54.89.179.75:80 check
    server 141730-web-02 18.214.87.172:80 check"

sudo bash -c "echo -e '$SERVER_CONFIG' >> /etc/haproxy/haproxy.cfg"

sudo systemctl enable haproxy
