#!/usr/bin/env bash
# configure SSH client to connect to server without typing a password

Host server1
    HostName 54.89.179.75
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
